export const cuisines = [
  "african",
  "asian",
  "american",
  "british",
  "cajun",
  "caribbean",
  "chinese",
  "easter european",
  "french",
  "german",
  "greek",
  "indian",
  "irish",
  "italian",
  "japanese",
  "jewish",
  "korean",
  "latin american",
  "mediterranean",
  "mexican",
  "middle eastern",
  "nordic",
  "southern",
  "spanish",
  "thai",
  "vietnamese",
];

export const recipes = [
  {
    id: 641803,
    title: "Easy & Delish! ~ Apple Crumble",
    image:
      "https://spoonacular.com/recipeImages/Easy---Delish--Apple-Crumble-641803.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 4,
    likes: 1,
  },
  {
    id: 645152,
    title: "Grandma's Apple Crisp",
    image:
      "https://spoonacular.com/recipeImages/Grandmas-Apple-Crisp-645152.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 6,
    likes: 1,
  },
  {
    id: 657563,
    title: "Quick Apple Ginger Pie",
    image:
      "https://spoonacular.com/recipeImages/Quick-Apple-Ginger-Pie-657563.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 6,
    likes: 1,
  },
  {
    id: 639487,
    title: "Cinnamon Sugar Fried Apples",
    image:
      "https://spoonacular.com/recipeImages/Cinnamon-Sugar-Fried-Apples-639487.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 8,
    likes: 46,
  },
  {
    id: 643426,
    title: "Fresh Apple Cake With Caramel Sauce",
    image:
      "https://spoonacular.com/recipeImages/Fresh-Apple-Cake-With-Caramel-Sauce-643426.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 12,
    likes: 9,
  },
];

export const recipeInDetail = {
  vegetarian: false,
  vegan: false,
  glutenFree: true,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 21,
  gaps: "no",
  lowFodmap: false,
  ketogenic: false,
  whole30: false,
  servings: 10,
  sourceUrl:
    "http://www.epicurious.com/recipes/food/views/Char-Grilled-Beef-Tenderloin-with-Three-Herb-Chimichurri-235342",
  spoonacularSourceUrl:
    "https://spoonacular.com/char-grilled-beef-tenderloin-with-three-herb-chimichurri-156992",
  aggregateLikes: 0,
  creditText: "Epicurious",
  sourceName: "Epicurious",
  extendedIngredients: [
    {
      id: 1022009,
      aisle: "Ethnic Foods",
      image: "https://spoonacular.com/cdn/ingredients_100x100/chili-powder.jpg",
      name: "ancho chile powder",
      amount: 1.5,
      unit: "teaspoons",
      unitShort: "t",
      unitLong: "teaspoons",
      originalString:
        "1 1/2 teaspoons chipotle chile powder or ancho chile powder",
      metaInformation: [],
    },
    {
      id: 13926,
      aisle: "Meat",
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/beef-tenderloin.jpg",
      name: "beef tenderloin",
      amount: 3.5,
      unit: "pound",
      unitShort: "lb",
      unitLong: "pounds",
      originalString: "1 3 1/2-pound beef tenderloin",
      metaInformation: [],
    },
    {
      id: 1002030,
      aisle: "Spices and Seasonings",
      image: "https://spoonacular.com/cdn/ingredients_100x100/pepper.jpg",
      name: "black pepper",
      amount: 0.5,
      unit: "teaspoon",
      unitShort: "t",
      unitLong: "teaspoons",
      originalString: "1/2 teaspoon freshly ground black pepper",
      metaInformation: ["black", "freshly ground"],
    },
    {
      id: 1082047,
      aisle: "Spices and Seasonings",
      image: "https://spoonacular.com/cdn/ingredients_100x100/salt.jpg",
      name: "coarse kosher salt",
      amount: 1,
      unit: "tablespoon",
      unitShort: "T",
      unitLong: "tablespoon",
      originalString: "1 tablespoon coarse kosher salt",
      metaInformation: [],
    },
    {
      id: 10019334,
      aisle: "Baking",
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/brown-sugar-dark.jpg",
      name: "dark brown sugar",
      amount: 2,
      unit: "tablespoons",
      unitShort: "T",
      unitLong: "tablespoons",
      originalString: "2 tablespoons dark brown sugar",
      metaInformation: ["dark"],
    },
    {
      id: 11165,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/cilantro.png",
      name: "fresh cilantro",
      amount: 2,
      unit: "cups",
      unitShort: "c",
      unitLong: "cups",
      originalString: "2 cups (packed) stemmed fresh cilantro",
      metaInformation: ["fresh", "packed", "stemmed", "()"],
    },
    {
      id: 2064,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/mint.jpg",
      name: "fresh mint",
      amount: 1,
      unit: "cup",
      unitShort: "c",
      unitLong: "cup",
      originalString: "1 cup (packed) stemmed fresh mint",
      metaInformation: ["fresh", "packed", "stemmed", "()"],
    },
    {
      id: 11297,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/parsley.jpg",
      name: "fresh parsley",
      amount: 3,
      unit: "cups",
      unitShort: "c",
      unitLong: "cups",
      originalString: "3 cups (packed) stemmed fresh parsley",
      metaInformation: ["fresh", "packed", "stemmed", "()"],
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/garlic.jpg",
      name: "garlic cloves",
      amount: 3,
      unit: "",
      unitShort: "",
      unitLong: "",
      originalString: "3 garlic cloves, peeled",
      metaInformation: ["peeled"],
    },
    {
      id: 1002030,
      aisle: "Spices and Seasonings",
      image: "https://spoonacular.com/cdn/ingredients_100x100/pepper.jpg",
      name: "ground pepper",
      amount: 1,
      unit: "teaspoon",
      unitShort: "t",
      unitLong: "teaspoon",
      originalString: "1 teaspoon ground black pepper",
      metaInformation: ["black"],
    },
    {
      id: 9152,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/lemon-juice.jpg",
      name: "lemon juice",
      amount: 3,
      unit: "tablespoons",
      unitShort: "T",
      unitLong: "tablespoons",
      originalString: "3 tablespoons fresh lemon juice",
      metaInformation: ["fresh"],
    },
    {
      id: 4053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "https://spoonacular.com/cdn/ingredients_100x100/olive-oil.jpg",
      name: "olive oil",
      amount: 0.75,
      unit: "cup",
      unitShort: "c",
      unitLong: "cups",
      originalString: "3/4 cup olive oil",
      metaInformation: [],
    },
    {
      id: 4053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "https://spoonacular.com/cdn/ingredients_100x100/olive-oil.jpg",
      name: "olive oil",
      amount: 2,
      unit: "tablespoons",
      unitShort: "T",
      unitLong: "tablespoons",
      originalString: "2 tablespoons olive oil",
      metaInformation: [],
    },
    {
      id: 11821,
      aisle: "Produce",
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/red-bell-pepper.png",
      name: "red pepper",
      amount: 0.5,
      unit: "teaspoon",
      unitShort: "t",
      unitLong: "teaspoons",
      originalString: "1/2 teaspoon dried crushed red pepper",
      metaInformation: ["dried", "red", "crushed"],
    },
    {
      id: 1022068,
      aisle: "Oil, Vinegar, Salad Dressing",
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/red-wine-vinegar.jpg",
      name: "red wine vinegar",
      amount: 3,
      unit: "tablespoons",
      unitShort: "T",
      unitLong: "tablespoons",
      originalString: "3 tablespoons Sherry wine vinegar or red wine vinegar",
      metaInformation: ["red"],
    },
    {
      id: 1012047,
      aisle: "Spices and Seasonings",
      image: "https://spoonacular.com/cdn/ingredients_100x100/salt.jpg",
      name: "sea salt",
      amount: 1,
      unit: "teaspoon",
      unitShort: "t",
      unitLong: "teaspoon",
      originalString: "1 teaspoon fine sea salt",
      metaInformation: ["fine"],
    },
    {
      id: 11677,
      aisle: "Produce",
      image: "https://spoonacular.com/cdn/ingredients_100x100/shallots.jpg",
      name: "shallots",
      amount: 2,
      unit: "",
      unitShort: "",
      unitLong: "",
      originalString: "2 medium shallots, peeled, quartered",
      metaInformation: ["medium", "peeled", "quartered"],
    },
    {
      id: 1002028,
      aisle: "Spices and Seasonings",
      image: "https://spoonacular.com/cdn/ingredients_100x100/paprika.jpg",
      name: "sweet paprika",
      amount: 1,
      unit: "tablespoon",
      unitShort: "T",
      unitLong: "tablespoon",
      originalString: "1 tablespoon sweet smoked paprika*",
      metaInformation: ["smoked"],
    },
  ],
  id: 156992,
  title: "Char-Grilled Beef Tenderloin with Three-Herb Chimichurri",
  readyInMinutes: 45,
  image:
    "https://spoonacular.com/recipeImages/char-grilled-beef-tenderloin-with-three-herb-chimichurri-156992.jpg",
  imageType: "jpg",
  instructions:
    "PreparationFor spice rub:                                        Combine all ingredients in small bowl.                                                                            Do ahead: Can be made 2 days ahead. Store airtight at room temperature.                                    For chimichurri sauce:                                        Combine first 8 ingredients in blender; blend until almost smooth. Add 1/4 of parsley, 1/4 of cilantro, and 1/4 of mint; blend until incorporated. Add remaining herbs in 3 more additions, pureeing until almost smooth after each addition.                                                                            Do ahead: Can be made 3 hours ahead. Cover; chill.                                    For beef tenderloin:                                        Let beef stand at room temperature 1 hour.                                                                            Prepare barbecue (high heat). Pat beef dry with paper towels; brush with oil. Sprinkle all over with spice rub, using all of mixture (coating will be thick). Place beef on grill; sear 2 minutes on each side. Reduce heat to medium-high. Grill uncovered until instant-read thermometer inserted into thickest part of beef registers 130F for medium-rare, moving beef to cooler part of grill as needed to prevent burning, and turning occasionally, about 40 minutes. Transfer to platter; cover loosely with foil and let rest 15 minutes. Thinly slice beef crosswise. Serve with chimichurri sauce.                                                                            *Available at specialty foods stores and from tienda.com.",
};

export const detailedRecipesList = [
  {
    id: 618390,
    title: "Quick Apple Pies",
    image: "https://img.spoonacular.com/recipes/618390-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1123,
        amount: 1,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "egg",
        original: "1 Egg",
        originalName: "Egg",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 10018338,
        amount: 1,
        unit: "sheet",
        unitLong: "sheet",
        unitShort: "sheet",
        aisle: "Frozen",
        name: "pastry dough",
        original: "1 sheet Pastry Dough",
        originalName: "Pastry Dough",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/dough.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 5,
        unit: "medium",
        unitLong: "mediums",
        unitShort: "medium",
        aisle: "Produce",
        name: "apples",
        original: "5 medium Apples",
        originalName: "Apples",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 1005,
  },
  {
    id: 615374,
    title: "Mom's Apple Pie",
    image: "https://img.spoonacular.com/recipes/615374-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2010,
        amount: 1,
        unit: "tsp",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "cinnamon",
        original: "1 to 1 ½ tsp. cinnamon",
        originalName: "cinnamon",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 1145,
        amount: 3,
        unit: "tbsp",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "3 tbsp. unsalted butter",
        originalName: "unsalted butter",
        meta: ["unsalted"],
        extendedName: "unsalted butter",
        image:
          "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 8,
        unit: "large",
        unitLong: "larges",
        unitShort: "large",
        aisle: "Produce",
        name: "apples",
        original: "8 large apples, peeled, cored and sliced",
        originalName: "apples, peeled, cored and sliced",
        meta: ["cored", "peeled", "sliced"],
        image: "https://img.spoonacular.com/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 434,
  },
  {
    id: 611026,
    title: "Apple Crisp III",
    image: "https://img.spoonacular.com/recipes/611026-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1077,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "3/4 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
      {
        id: 8120,
        amount: 2,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cereal",
        name: "rolled oats",
        original: "2 cups rolled oats",
        originalName: "rolled oats",
        meta: [],
        image:
          "https://img.spoonacular.com/ingredients_100x100/rolled-oats.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 2.5,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "macintosh apples",
        original: "2 1/2 cups Macintosh apples - peeled, cored and quartered",
        originalName: "Macintosh apples - peeled, cored and quartered",
        meta: ["cored", "peeled", "quartered"],
        image: "https://img.spoonacular.com/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 138,
  },
  {
    id: 47950,
    title: "Cinnamon Apple Crisp",
    image: "https://img.spoonacular.com/recipes/47950-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 93674,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "land o cinnamon sugar butter spread",
        original: "1/2 cup Land O Lakes® Cinnamon Sugar Butter Spread",
        originalName: "Land O Lakes® Cinnamon Sugar Butter Spread",
        meta: ["lakes®"],
        image:
          "https://img.spoonacular.com/ingredients_100x100/cinnamon-sugar-butter.png",
      },
      {
        id: 8120,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cereal",
        name: "old-fashioned oats",
        original: "3/4 cup uncooked old-fashioned oats",
        originalName: "uncooked old-fashioned oats",
        meta: ["uncooked"],
        image:
          "https://img.spoonacular.com/ingredients_100x100/rolled-oats.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 6,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "apples",
        original: "6 medium (6 cups) apples, peeled, cored, sliced",
        originalName: "medium apples, peeled, cored, sliced",
        meta: ["cored", "peeled", "sliced"],
        image: "https://img.spoonacular.com/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 35,
  },
  {
    id: 70306,
    title: "Easy Cinnamon Apple Pie",
    image: "https://img.spoonacular.com/recipes/70306-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11408,
        amount: 1.6666666,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Frozen",
        name: "hershey's cinnamon chips",
        original: "1-2/3 cups (10-oz. pkg.) HERSHEY'S Cinnamon Chips, divided",
        originalName: "(10-oz. pkg.) HERSHEY'S Cinnamon Chips, divided",
        meta: ["divided", "(10-oz. pkg.)"],
        image:
          "https://img.spoonacular.com/ingredients_100x100/french-fries-isolated.jpg",
      },
      {
        id: 18334,
        amount: 15,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Refrigerated",
        name: "pie crusts",
        original:
          "1 package (15 oz.) refrigerated pie crusts, or pastry for double-crust 9-inch pie",
        originalName:
          "package refrigerated pie crusts, or pastry for double-crust 9-inch pie",
        meta: ["refrigerated", "for double-crust pie"],
        extendedName: "refrigerated pie crusts",
        image: "https://img.spoonacular.com/ingredients_100x100/pie-crust.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 40,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "apples",
        original:
          "2 cans (20-oz. each) sliced apples (not pie filling), drained *",
        originalName: "cans each) sliced apples (not pie filling), drained",
        meta: ["drained", "sliced", "canned", "(not pie filling)"],
        extendedName: "canned apples",
        image: "https://img.spoonacular.com/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 5,
  },
];
